Myton_Django/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.template.loader import add_to_builtins
add_to_builtins('apps.templatetags.myton_tags')

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', 'Myton_Django.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       # url(r'^staff/$', 'staff.views.home'),
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^chaining/', include('smart_selects.urls')),

                       # url(r'^trade/$', 'trade.views.hello'),
                       # url(r'^trade/$', 'trade.views.home'),
                       url(r'^trade/create/$', 'trade.views.create'),
                       url(r'^latest-news/$', 'apps.article.views.latest_news'),
                       url(r'^article/(?P<slug>[\w-]+)/$', 'apps.article.views.detail_article'),
                       # url(r'^part-search/$', 'trade.views.partsearch'),
                       url(r'^search/$', 'Myton_Django.views.search'),
                       url(r'^downloads/$',
                           'apps.files.views.list_file_downloads'),
                       url(r'^my-details/$', 'apps.customer.views.details'),
                       url(r'^my-orders/$', 'apps.order.views.myorder'),
                       url(r'^orderreview/(\w+)$', 'apps.order.views.order_review'),
                       url(r'^invoice/(\w+)$', 'apps.order.views.invoice'),
                       url(r'^about/$', 'trade.views.about'),
                       url(r'^login/$', 'trade.views.login'),
                       url(r'^language/(?P<language>[a-z\-]+)/$',
                           'trade.views.language'),

                       # cart
                       url(r'^addcart/(\d+)/$', 'Myton_Django.views.add_to_cart'),
                       url(r'^updatecart/(\d+)/(\d+)$', 'Myton_Django.views.update_cart'),
                       url(r'^my-cart/$', 'Myton_Django.views.mycart'),
                       url(r'^clear-cart/$', 'Myton_Django.views.clear_cart'),
                       url(r'^checkout/$', 'apps.order.views.checkout'),
                       url(r'^get_delivery/(\w+)$', 'apps.order.views.get_delivery'),
                       url(r'^get_detail_order/(\d+)$', 'apps.order.views.get_detail_order'),                       

                       # user auth urls
                       url(r'^accounts/login/$', auth_views.login,
                           {'template_name': 'safe_login.html'}, name='auth_login'),
                       url(r'^accounts/logout/$', auth_views.logout,
                           {'next_page': '?next=/'}, name='auth_logout'),
                       url(r'^accounts/register/$',
                           'apps.customer.views.register_user'),
                       url(r'^accounts/change_password/$',
                           'apps.customer.views.change_password'),
                       url(r'^accounts/register_success/$',
                           'apps.customer.views.register_success'),


                       # url(r'^latest-news/$', include('trade.urls')),

                       # toms experiment - 03.07.2014
                       url(r'^experiment/$',
                           'Myton_Django.views.ua_display_good1'),

                       )

trade/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'^all/$', 'trade.views.articles'),
                       url(r'^get/(?P<article_id>\d+)/$',
                           'trade.views.article'),
                       url(r'^language/(?P<language>[a-z\-]+)/%',
                           'trade.views.language'),
                       url(r'^create/$', 'trade.views.create'),
                       )

apps/article/models.py
from django.db import models
from django.template.defaultfilters import slugify
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from tinymce.models import HTMLField
import uuid
import os

# Create your models here.

class Article(models.Model):
    def get_file_path(instance, filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('article', filename)

    title = models.CharField(max_length=255, null=True)
    slug = models.SlugField(max_length=255, null=True, editable=False)
    content = HTMLField(blank=True, null=True)
    image = models.ImageField(upload_to=get_file_path, null=True)
    image_thumb = ImageSpecField(
        source='image', processors=[ResizeToFill(200, 100)],
        format='JPEG', options={'quality': 60})
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)

    def __unicode__(self):
        return unicode(self.creation_date)

class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'))
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    surcharge = models.DecimalField(max_digits=18, decimal_places=2, default=0, verbose_name=_('surcharge'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * (self.unit_price + self.surcharge)
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

apps/setup/forms.py
from django import forms
from apps.setup.models import PostageRate

class DeliveryServiceForm(forms.Form):
    service = forms.ModelChoiceField(queryset=PostageRate.objects.all(), widget = forms.Select(attrs={'class':'form-control'}))

apps/article/views.py
from django.shortcuts import render, render_to_response
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.template import Context, RequestContext
from Myton_Django.views import custom_proc
from apps.article.models import Article
# Create your views here.

@login_required
def latest_news(request):
    last_article = Article.objects.all()
    data = {'breadcrumb':'latest-news', 'last_article':last_article}
    return render_to_response('article/latest_news.html', data, context_instance=RequestContext(request, processors=[custom_proc]))

@login_required
def detail_article(request, slug):
    article = Article.objects.get(slug=slug)
    data = {'breadcrumb':'latest-news', 'article':article}
    return render_to_response('article/article_detail.html', data, context_instance=RequestContext(request, processors=[custom_proc]))

cart/views.py
# Create your views here.

templates/article.html
{% extends "base.html" %}

{% block main_area %}
<ul>
    {{ article.title }} - 
    {{ article.body }}
</ul>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Myton Automotive Trade Portal</title>
<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}css/bootstrap-theme.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}css/main.css" rel="stylesheet" type="text/css">


  <!-- HTML5 shim for IE backwards compatibility -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>
<div class="container">
<body class ="body">

<div class="image_header clearfix">
    <div class="col-md-6"><a href="/"><img src="{{ STATIC_URL }}img/mainlogo.jpg" width="180" height="73"></a></div>    
    <div class="row">
    <div class="well well-lg col-md-3 pull-right account-cart-box">
      <a href="/my-cart" class="account-cart"><span class="glyphicon glyphicon-shopping-cart"></span> Cart {% if cart.count %}<span class="badge">{{cart.count}}</span>{% endif %}</a>
      <a href="/my-details" class="account-cart"><span class="glyphicon glyphicon-user"></span> Account</a>
    </div>
    </div>
    <div class="row">
    <div class="pull-right">
      <a href="/accounts/change_password" class="btn btn-link" style="margin-right:0px">Change Password</a> | 
      <a href="/accounts/logout" class="btn btn-link" style="margin-right:0px">Logout</a>
    </div>    
    </div>    
</div>

<div class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li {% if breadcrumb == 'search' %}class="active"{% endif %}><a href="/search/">Part Seach</a></li>
              <li {% if breadcrumb == 'latest-news' %}class="active"{% endif %}><a href="/latest-news">Latest News</a></li>
              <li {% if breadcrumb == 'myorder' %}class="active"{% endif %}><a href="/my-orders">My Orders</a></li>              
              <li {% if breadcrumb == 'downloads' %}class="active"{% endif %}><a href="/downloads">Downloads</a></li>              
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

<div>
{% if messages %}
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
    </div>
    {% endfor %}
{% endif %}

    {% block main_area %}

    {% endblock main_area %}
</div>

<div class="well well-sm" style="margin-top:20px">{% include "footer.html"%}</div>

<div>
    {% block side_bar %}

    {% endblock side_bar %}
</div>

<!-- <script src="http://code.jquery.com/jquery-latest.js"></script> -->
<script src="{{ STATIC_URL }}js/jquery-1.7.2.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script type="text/javascript">
$(function(){  
  $(".theform input").addClass('form-control');

  $('#country_delivery').change(function(){ 
    $('#delivery_service').html('loading');
    $('#order_detail').html('<div class="form-group pull-right"><div class="col-sm-12"><span class="btn btn-success" disabled="disabled">Continue</span></div>');
    country = $(this).val();
    $.ajax ({
      url: '/get_delivery/'+ country,
      type: "GET",
      success: function(msg){
        // alert(msg);
        $('#delivery_service').html(msg);
      },
    });
  });

  $('#id_service').live('change',function(){ 
    var service = $(this).val();
    $('#order_detail').html('loading');
    $.ajax ({
      url: '/get_detail_order/'+service,
      type: "GET",
      success: function(msg){
        $('#order_detail').html(msg);
      },
    });
  });

  $('.part_tooltip').tooltip({placement:'bottom'})
});

function addtocart(url){
  $.ajax ({
    url: url ,
    type: "GET",
    success: function(msg){
      //alert(msg); 
      window.location.href = '/my-cart';
    },
  });
}

function clear_cart(){
  $.ajax ({
    url: '/clear-cart' ,
    type: "GET",
    success: function(msg){
      alert(msg); 
      window.location.href = '/my-cart';
    },
  });
}
function change_qty(id,val){
  $.ajax ({
    url: '/updatecart/'+id+'/'+val ,
    type: "GET",
    success: function(msg){
      window.location.href = '/my-cart';
    },
  });
}

</script>
</body>
</div>
</html>

templates/create_article.html
{% extends "base.html" %}

{% block side_bar %}
<ul>
    <li><a href="/trade/all">Cancek</a></li>
</ul>

{% endblock %}

{% block main_area %}

<form action="/trade/create/" method="post">{% csrf_token %}
<ul>
    {{ form.as_ul }}
</ul>

<input type="submit" name="submit" value="Create Article">
</form>

{% endblock %}

templates/experiments.html
{% extends "base.html" %}

{% block main_area %}

<h3>Experiments Page</h3>
<div>
<p>

    <form action="/search/" method="post">{% csrf_token %}
    <label for="your_name">Search: </label>
    <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
    <input type="submit" value="OK">
</form>
</div>

<p>
    <table class="table">
    <thead>
    <tr>
        <td>Database ID</td>
        <td>Part Number</td>
        <td>Description</td>
        <td>RRP Price</td>
        <td>Issued In</td>
        <td>Surcharge</td>
        <td>Your Buy Price</td>
    </tr>
    </thead>
    </table>

   <tbody>
    <tr>
       <td>{{ id_number }}</td>
    </tr>

   </tbody>
</p>



</p>


</div>
{% endblock main_area %}

templates/finish_order.html
{% extends "base.html" %}

{% block main_area %}
<h3>Finish</h3>
<div>Thanks you for your order. Please confirm your payment.</div>
{% endblock main_area %}

templates/footer.html
Copyright - Myton Automotive 2014

templates/invalid_login.html
{%  extends "login.html" %}

{%  block main_area %}

    <h2>Your login details are invalid</h2>
    <p>Click <a href="/accounts/login/">here</a> to login again.</p>

{%  endblock main_area %}

templates/login (1).html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}
    <title>Myton Automotive Login Page</title>



</head>

<body>
	<div id="page">

<div class="image_header">
    <img src="../static/img/mainlogo.jpg" width="180" height="73">
</div>

    <div id="content">


        {% block content %} This is where the login details boxes should show {% endblock content %}



	</div>

</body>
</html>

templates/login.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Myton Automotive Trade Portal Login</title>
<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}css/bootstrap-theme.css" rel="stylesheet" type="text/css">
<link href="{{ STATIC_URL }}css/main.css" rel="stylesheet" type="text/css">
<!-- HTML5 shim for IE backwards compatibility -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<div class="container">
<body class ="body">
<div class="image_header">
    <img src="{{ STATIC_URL }}img/mainlogo.jpg" width="180" height="73">
</div>

<div>
    {% block content %}

    {% endblock content %}
</div>


<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>

<div class="well well-sm">{% include "footer.html"%}</div>

</body>
</div>
<script type="text/javascript">
$(document).ready(function(){
  $(".form-signin input").addClass('form-control');
 });
</script>
</html>

templates/my-detail.html
{% extends "base.html" %}

{% block main_area %}

<h3>Your details</h3>
    <p>Make any changes to your details here.</p>



{% endblock main_area %}

templates/my-orders.html
{% extends "base.html" %}

{% block main_area %}

<h3>My Orders</h3>
    <p>Overview of your orders</p>



{% endblock main_area %}

templates/order_complete.html
{% extends "base.html" %}

{% block main_area %}
<h3>Finish</h3>
<div>Thanks you for your order. Please confirm your payment.</div>
{% endblock main_area %}

templates/partsearch.html
{% extends "base.html" %}


{% block main_area %}
<h3>Part Number Lookup</h3>
<form action="/search/" method="get">
    {% csrf_token %}
    <input type="text" name="q">
    <input type="submit" value="Search">
</form> 


<div>
    <p>{% if search_query %}Search Query was <strong>{{ search_query }}</strong>{% endif %}</p>
    <p>Results:</p>

<table class="table">
    <tr><th>Part Number</th><th>Description</th><th>Retail Price</th><th>Your Price</th><th>Supersesions</th><th>Surcharge</th><th></th></tr>

    {% if part %}
    {% for part_number in part %}
    <tr>
        <td>{{ part_number.part_number }}</td>
        <td>{{ part_number.description }}</td>
        <td>{{ part_number.rrp_price }}</td>
        <td>{{ part_number.buy_price }}</td>
        <td>{{ part_number.supersessions }}</td>
        <td>{{ part_number.surcharge }}</td>
        <td><a href="" onclick="addtocart('/addcart/{{part_number.id}}'); return false;" class="btn btn-success btn-sm">Order</a></td>
    </tr>
    {% endfor %}
    {% else %}
    <tr><td colspan="7" class="text-center">No Result</td></tr>
    {% endif %}

</table>

</div>

{% endblock main_area %}

templates/safe_login.html
{% extends "login.html" %}

{% block content %}

<div class="container">
<div class="panel panel-default" style="max-width: 330px; margin: 50px auto;">
<div class="panel-heading">
<h3 class="panel-title">Login</h3>
</div>
<div class="panel-body">
<form action="" method="post" class="form-horizontal form-signin" role="form">
{% csrf_token %}
{% for field in form.visible_fields %}
    <div class="form-group">
        <label class="col-sm-4 control-label">{{ field.label }}</label>
        <div class="col-sm-8">
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}
              <div class="alert alert-danger alert-validation">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ error|escape }}
              </div>
            {% endfor %}
        {% endif %}
        </div>
    </div>
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-4">
        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
        </div>
    </div>
</form>
<a href="/accounts/register/" class="btn btn-link pull-right">Don't have account? Register here.</a>
</div>
</div>
</div>

{% endblock %}